name: Generate Terraform README docs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  docs:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@cca78c27ac9e2b6545debf2ecae9df930fd3461c # v1.2.2
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
