name: Terraform Static Code Analysis

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform-static-analysis.yml'

permissions:
  contents: read

jobs:
  terraform-static-analysis:
    permissions:
      pull-requests: write
    name: Terraform Static Analysis
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' && github.event_name != 'schedule'
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Run Analysis
        uses: ministryofjustice/github-actions/terraform-static-analysis@721b0f273fc8356611cb18b3dfc02074d59217da # v18.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scan_type: changed
          trivy_severity: HIGH,CRITICAL
          trivy_ignore: ./.trivyignore.yaml
          checkov_exclude: CKV_GIT_1,CKV_AWS_126,CKV2_AWS_38,CKV2_AWS_39
          tflint_exclude: terraform_unused_declarations
          tflint_call_module_type: none
          tfsec_trivy: trivy
  

  terraform-static-analysis-full-scan:
    permissions:
      pull-requests: write
    name: Terraform Static Analysis - scan all directories
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
    - name: Checkout
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      with:
        fetch-depth: 0
    - name: Run Analysis
      uses: ministryofjustice/github-actions/terraform-static-analysis@721b0f273fc8356611cb18b3dfc02074d59217da # v18.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        scan_type: full
        tfsec_exclude: AWS089, AWS099, AWS009, AWS097, AWS018
        checkov_exclude: CKV_GIT_1
        tflint_exclude: terraform_unused_declarations
        tflint_call_module_type: none
